### PR TITLE
Run jobs nightly

### PR DESCRIPTION
**Pull request by hugobuddel**
So we are made aware of issues that cause things to fail early, see e.g. the failures in #52

### CODE REVIEW

**Review by teutoburg — APPROVED** [review]
Sure why not. Maybe we will need to "space out" our nightly runs, i.e. don't start all of them at the same time, if it turns out that some rate limit regularly exeeds. But we'll see about that I guess...

**Comment by teutoburg** [comment]
Rebased to include #54, seems to work now.

**Comment by teutoburg** [comment]
> I refactored the webtests to not run nightly, or run by default. ScopeSim_Data can run those webtests once, they don't have to be run with the full matrix.

I liked having all tests called from one workflow file. That way they all show up at once when viewed on the actions tab. I agree with not running the webtests nightly, but I'd prefer to still have them in the same workflow file. The syntax should allow for some if-statement on the webtests job, something [like this](https://stackoverflow.com/a/69332348/8467078) perhaps.

**Comment by hugobuddel** [comment]
> > I refactored the webtests to not run nightly, or run by default. ScopeSim_Data can run those webtests once, they don't have to be run with the full matrix.
> 
> I liked having all tests called from one workflow file. That way they all show up at once when viewed on the actions tab. I agree with not running the webtests nightly, but I'd prefer to still have them in the same workflow file. The syntax should allow for some if-statement on the webtests job, something [like this](https://stackoverflow.com/a/69332348/8467078) perhaps.

The webtests should also not run for PRs, e.g., they failed here, so I split them up. Or at least they should not run with the full matrix when they are ran automatically.

Having them as a separate workflow seems the cleanest solution to me.

**Comment by hugobuddel** [comment]
Like this?

Just squash and merge this if this change works for you  :smile:

**Comment by hugobuddel** [comment]
Pfffff this should not be merged, because we should not have a daily reminder that the tests are broken, see #37 . Marking as draft

**Comment by teutoburg** [comment]
> The webtests should also not run for PRs, e.g., they failed here, so I split them up. Or at least they should not run with the full matrix when they are ran automatically.

I don't understand why we would not want to have them running for PRs? The "full matrix" for the webtests only consists of two combinations anyway. What I'm I missing?

**Comment by hugobuddel** [comment]
> > The webtests should also not run for PRs, e.g., they failed here, so I split them up. Or at least they should not run with the full matrix when they are ran automatically.
> 
> I don't understand why we would not want to have them running for PRs? The "full matrix" for the webtests only consists of two combinations anyway. What am I missing?

They already failed here in this PR. It is annoying if we have to rerun the tests multiple times for each PR just to get the network tests to pass.

**Comment by hugobuddel** [comment]
At the moment all tests are green, but in the previous run they failed: https://github.com/AstarVienna/speXtra/actions/runs/11496374587/job/31997866855 with 
```
E                   requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='svo2.cab.inta-csic.es', port=80): Max retries exceeded with url: /theory/fps3/fps.php?ID=2MASS/2MASS.Ks (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001EBF7D7C950>, 'Connection to svo2.cab.inta-csic.es timed out. (connect timeout=None)'))
```

(That was a failure in the 'offline' tests, because they were not actually offline, hence my sigh and making this a Draft.)

**Pull request merged**
