### PR TITLE
Allow internal updates

### PR DESCRIPTION
**Pull request by teutoburg**
This allows our own package to be updated while still in "dev mode", aka < v1.0.

Perhaps this should be rolled out to all dependency specifications for our own packages.

### CODE REVIEW

**Review by hugobuddel — CHANGES_REQUESTED** [review]
This  might (read: will) cause problems, because now any version of `astar-utils` is acceptable (if I understand correctly), but speXtra might not work with older versios.

Say someone has astar-utils 0.1.3 installed, and speXtra 0.33. We add proper logging to speXtra and release 0.40 that uses `get_logger()` from astar-utils 0.2.0. The user subsequently upgrades speXtra for some reason. Then pip will realize that the astar-utils dependency is already fulfilled and will keep astar-utils at 0.1.3 which does not have get_logger. Now the user has a broken installation.

This broken upgrading is something that happened frequently in the past, which led to the creation of the minimum dependencies test, to ensure that pyproject.toml does only list dependencies that actually work.

We replaced the minimum dependencies test with a minimal poetry.lock file, which also worked well. However, this poetry.lock is not in sync with pyproject.toml anymore it seems.

I propose we simply do
```
astar-utils = ">=0.1.3"
```
because it is not necessary to use the caret, since we are in full control of astar-utils anyway.

**Comment by teutoburg** [comment]
Yeah, you're right. This was a silly idea. Let's just do the ">=" instead 👍

**Comment by teutoburg** [comment]
> However, this poetry.lock is not in sync with pyproject.toml anymore it seems.

I checked (using `poetry show -T --with test --with docs`) on this branch and all versions seem to match those specified as minimums in the pyproject.toml. Did I miss any?

**Comment by hugobuddel** [comment]
> > However, this poetry.lock is not in sync with pyproject.toml anymore it seems.
> 
> I checked (using `poetry show -T --with test --with docs`) on this branch and all versions seem to match those specified as minimums in the pyproject.toml. Did I miss any?

I meant it was inconsistent with the `^0` it `pyproject.toml`. I believe you if you say it is consistent now.

Not sure about `allow-prereleases`. It would be fine to use `allow-preleases` for the dependencies of unreleased packages, or when the package itself is a pre-release, but for normal PyPI releases I think we should restrict ourselves to normal releases as dependencies. Because otherwise there would effectively be no difference between a pre-release and a normal release. I'm going to assume that is your plan.

**Review by hugobuddel — APPROVED** [review]

**Pull request merged**
